commitizen:
  bitbucket_repo: xayon/cz_bitbucket_jira_conventional
  jira_base_url: https://myproject.atlassian.net
  jira_prefix: XX-
  name: cz_bitbucket_jira_conventional
  tag_format: v$version
  version: 1.1.0
